// Regenerates fixtures/ts_reference.json (and the identical copy in sdks/stark-pca-plonky3/fixtures) from the TypeScript reference risk model
// (@atlasauth/pca: riskScore / admit). Run from the repo root after `pnpm --filter @atlasauth/pca build`:
//   node sdks/stark-pca/tests/gen_ts_reference.mjs
// The JSON is OUTPUT of the TS reference implementation (not an official standard vector).
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const pca = require(join(here, '../../../packages/pca/dist/index.js'));
const { riskScore, admit, requiredThreshold, DEFAULT_RISK_POLICY } = pca;
const S = 1_000_000;
const q = (x) => Math.round(x * S);

const policy = DEFAULT_RISK_POLICY;
const W = policy.weights;
const cases = [
  ['compliant (stark-pca Witness::compliant)', [0.1, 0.9, 0.05, 0, 0.95, 0.1], 1.0, true, true],
  ['all risk maximal, no budget', [0.9, 0.1, 0.9, 0.9, 0.1, 0.9], 0, true, true],
  ['compliant risk, predicate mismatch', [0.1, 0.9, 0.05, 0, 0.95, 0.1], 1.0, false, true],
  ['compliant risk, caveats unsatisfied', [0.1, 0.9, 0.05, 0, 0.95, 0.1], 1.0, true, false],
  ['tier-1 risk but budget below cost', [0.1, 0.9, 0.05, 0, 0.95, 0.1], 0.06, true, true],
  ['tier-1 risk, budget just above cost', [0.1, 0.9, 0.05, 0, 0.95, 0.1], 0.07, true, true],
  ['tier-2 risk (just above theta1)', [0.4, 0.5, 0.2, 0.1, 0.5, 0.3], 1.0, true, true],
  ['zero risk, zero budget', [0, 1, 0, 0, 1, 0], 0, true, true],
  ['mid risk 0.2, ample budget', [0.3, 0.7, 0.2, 0.1, 0.8, 0.2], 1.0, true, true],
  ['taint heavy', [0.1, 0.9, 0.05, 0.9, 0.95, 0.1], 1.0, true, true],
];
// Independent (BigInt) split of 256-bit hex commitments into big-endian `limbBits`-bit limbs.
const split = (hex, limbBits) => {
  const v = BigInt('0x' + hex);
  const n = 256 / limbBits;
  return Array.from({ length: n }, (_, i) => ((v >> BigInt(limbBits * (n - 1 - i))) & ((1n << BigInt(limbBits)) - 1n)).toString());
};
const commitmentVectors = [
  'a1b2c3d4e5f60718293a4b5c6d7e8f90fedcba98765432100123456789abcdef',
  '0f1e2d3c4b5a69788796a5b4c3d2e1f0112233445566778899aabbccddeeff00',
  '0'.repeat(63) + '1',
  'f'.repeat(64),
].map((h) => ({ hex: h, limbs_u64_be: split(h, 64), limbs_u32_be: split(h, 32) }));
const out = {
  description:
    'Output of the TypeScript reference risk model (@atlasauth/pca riskScore/admit) for the default risk policy, used to cross-check the Rust STARK semantics. Generated by tests/gen_ts_reference.mjs; not an official standard vector.',
  scale: S,
  commitment_limb_vectors: commitmentVectors,
  policy: {
    weights_scaled: [W.alpha, W.beta, W.gamma, W.delta, W.epsilon, W.zeta].map(q),
    theta1_scaled: q(policy.theta1),
    kappa: policy.kappa,
    bmax_scaled: q(policy.bMax),
  },
  cases: cases.map(([name, inp, B, pm, co]) => {
    const r = riskScore(
      { semanticDistance: inp[0], reversibility: inp[1], blastRadius: inp[2], taint: inp[3], confidence: inp[4], age: inp[5] },
      W,
    );
    const a = admit(r, { B, tau: 0 }, policy);
    return {
      name,
      inputs_scaled: inp.map(q),
      budget_scaled: q(B),
      predicate_match: pm,
      caveats_ok: co,
      ts_risk: r,
      ts_required_tier: requiredThreshold(r, policy).t,
      ts_admit: a.admit,
      ts_allow: a.admit && pm && co,
    };
  }),
};
const json = JSON.stringify(out, null, 2) + '\n';
writeFileSync(join(here, '../fixtures/ts_reference.json'), json);
// stark-pca-plonky3 shares the same reference (it adds the 32-bit limb split).
writeFileSync(join(here, '../../stark-pca-plonky3/fixtures/ts_reference.json'), json);
console.log('wrote', out.cases.length, 'cases');
